export const SPOTS = [
    {
        id: 1,
        name: "Misty Forest Reserve",
        location: "Coorg, Karnataka",
        tag: "Forest",
        price: "₹4,200",
        unit: "/ night",
        desc: "Ancient canopy walks, firefly trails & morning fog that swallows the world.",
        gradient: "linear-gradient(145deg,#040c06 0%,#0d2b1a 35%,#1a5c35 65%,#2d8a50 100%)",
        accent: "#7fb069",
        image: "https://zhanfg2pg2.ufs.sh/f/c8fuuCqs4lu2iIFU5bKEqLJiCV1YMgvynGTPHWueSKxXOAQt",
        video: "https://zhanfg2pg2.ufs.sh/f/c8fuuCqs4lu23PPJnckpRcn6sTu4vioaKWgMXG0rb89FPVDt",
    },
    {
        id: 2,
        name: "Alpine Summit Hideaway",
        location: "Manali, Himachal",
        tag: "Mountain",
        price: "₹6,800",
        unit: "/ night",
        desc: "Snow-capped ridgelines, stargazing decks & the silence of a thousand peaks.",
        gradient: "linear-gradient(145deg,#060a12 0%,#111e30 35%,#1e3d60 65%,#3a6890 100%)",
        accent: "#6ab4d8",
        image: "https://zhanfg2pg2.ufs.sh/f/c8fuuCqs4lu2SjJuVYDIk7xBnRCN398vFeADlMOqo4XhsdrJ",
        video: "https://zhanfg2pg2.ufs.sh/f/c8fuuCqs4lu2gEHyp1xGR7ExUZ3e0OwQzWk48riScvdDBJAo",
    },
    {
        id: 3,
        name: "Pillar Rocks",
        location: "Kodaikanal, Tamil Nadu",
        tag: "Mountain",
        price: "₹5,500",
        unit: "/ night",
        desc: "Vertically aligned granite boulders towering 400 feet (122m) above the valley floor",
        gradient: "linear-gradient(145deg,#040a18 0%,#0a1e40 35%,#1a3e80 65%,#2e6aaa 100%)",
        accent: "#4ab0e0",
        image: "https://zhanfg2pg2.ufs.sh/f/c8fuuCqs4lu2EtdycXcNm4gZS0G63lf5oKycB7RPMstJbxFi",
        video: "https://zhanfg2pg2.ufs.sh/f/c8fuuCqs4lu26ITTehbZQCE0jxosZDv3NetW2dn4UhpabyPO",
    },
    {
        id: 4,
        name: "Sacred Valley Sanctuary",
        location: "Munnar, Kerala",
        tag: "Valley",
        price: "₹3,900",
        unit: "/ night",
        desc: "Rolling tea gardens, mist-laden valleys and the scent of cardamom at every turn.",
        gradient: "linear-gradient(145deg,#060e04 0%,#0e2208 35%,#1e4a10 65%,#38801c 100%)",
        accent: "#82c254",
        image: "https://zhanfg2pg2.ufs.sh/f/c8fuuCqs4lu2tb8LSbruDb8i1q2OHQJav5UCsxMFoKz0SZBd",
        video: "https://zhanfg2pg2.ufs.sh/f/c8fuuCqs4lu29KGd125LwqQXRxY267OEPIGSy5zaVTbleuvs",
    },
    {
        id: 5,
        name: "Golden Dune Escape",
        location: "Jaisalmer, Rajasthan",
        tag: "Desert",
        price: "₹7,200",
        unit: "/ night",
        desc: "Silk-smooth dunes, camel silhouettes at twilight, and a sky full of fire.",
        gradient: "linear-gradient(145deg,#100a02 0%,#2a1c08 35%,#5a3c14 65%,#8a6a30 100%)",
        accent: "#c9a84c",
        image: "https://zhanfg2pg2.ufs.sh/f/c8fuuCqs4lu22IAiM5HJuKm6a1oNcAQX3HIrPExFsTwqd2C8",
        video: "https://zhanfg2pg2.ufs.sh/f/c8fuuCqs4lu2j3oU14VxeZkG20zp8mfcog1tTAObMUwQSjn9",
    },
    {
        id: 6,
        name: "Coastal Cliffs Perch",
        location: "Varkala, Kerala",
        tag: "Coastal",
        price: "₹5,100",
        unit: "/ night",
        desc: "Red laterite cliffs plunging into turquoise surf — breakfast above the Arabian Sea.",
        gradient: "linear-gradient(145deg,#020c10 0%,#082030 35%,#104058 65%,#226a80 100%)",
        accent: "#38b2c0",
        image: "https://zhanfg2pg2.ufs.sh/f/c8fuuCqs4lu2CxwCqEkMGXUlPiRduax6DmCerHFV93bWK0Bq",
        video: "https://zhanfg2pg2.ufs.sh/f/c8fuuCqs4lu23Pc6rcLpRcn6sTu4vioaKWgMXG0rb89FPVDt",
    },
];

export const ROOMS = [
    {
        id: 1,
        type: "Treehouse Suite",
        desc: "Suspended 30 ft in the canopy — sleep to the sound of leaves and birdsong.",
        guests: "2 Guests",
        size: "480 sq ft",
        gradient: "linear-gradient(135deg,#091c10,#1a4a22,#2d7a3d)",
        icon: "🌿",
        image: "https://assets.cntraveller.in/photos/60b9f801e1b212c19a816b9b/16:9/w_960,c_limit/vanya1.jpg",
    },
    {
        id: 2,
        type: "Riverside Cabin",
        desc: "Private deck over a rushing stream, wood-burning stove, raw timber walls.",
        guests: "4 Guests",
        size: "680 sq ft",
        gradient: "linear-gradient(135deg,#0d1a0a,#1e3d10,#3a6a20)",
        icon: "🏞️",
        image: "https://t3.ftcdn.net/jpg/09/18/71/36/360_F_918713625_g4lGndHyvLdubnnyXmps4S6j1ylxRT8X.jpg",
    },
    {
        id: 3,
        type: "Glamping Dome",
        desc: "Transparent geodesic dome — fall asleep under the Milky Way, wake to mist.",
        guests: "2 Guests",
        size: "320 sq ft",
        gradient: "linear-gradient(135deg,#06091a,#101e3a,#1e3a6a)",
        icon: "✨",
        image: "https://gos3.ibcdn.com/dd11e79e-18ae-4342-92b4-4b571e375a16.jpeg",
    },
];

export const PLANS = [
    {
        name: "Explorer",
        tagline: "For the curious wanderer",
        price: "₹999",
        period: "/ month",
        color: "rgba(127,176,105,.14)",
        border: "rgba(127,176,105,.25)",
        perks: [
            "Access to 20+ curated spots",
            "Basic room listings",
            "Community trail maps",
            "Email support",
        ],
        featured: false,
    },
    {
        name: "Wanderer",
        tagline: "Most popular · Best value",
        price: "₹2,499",
        period: "/ month",
        color: "rgba(26,92,53,.35)",
        border: "rgba(201,168,76,.45)",
        perks: [
            "Access to 100+ premium spots",
            "Priority room bookings",
            "Curated nature itineraries",
            "Concierge support 24/7",
            "10% off all rentals",
        ],
        featured: true,
    },
    {
        name: "Serenity",
        tagline: "For the discerning traveller",
        price: "₹5,999",
        period: "/ month",
        color: "rgba(10,26,14,.6)",
        border: "rgba(127,176,105,.2)",
        perks: [
            "Unlimited spot access",
            "Exclusive private retreats",
            "Personal nature guide",
            "Dedicated trip planner",
            "20% off all rentals",
            "Annual gifted getaway",
        ],
        featured: false,
    },
];

export const RENTS = [
    { label: "Per Night", from: "₹2,800", icon: "🌙" },
    { label: "Weekend (2N)", from: "₹5,200", icon: "🏕️" },
    { label: "Week-Long", from: "₹18,000", icon: "🌿" },
    { label: "Monthly", from: "₹65,000", icon: "🍃" },
];